// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module CNN_CNN_Pipeline_VITIS_LOOP_93_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        OutPool3_address0,
        OutPool3_ce0,
        OutPool3_q0,
        OutPool3_address1,
        OutPool3_ce1,
        OutPool3_q1,
        OutPool3_1_address0,
        OutPool3_1_ce0,
        OutPool3_1_q0,
        OutPool3_1_address1,
        OutPool3_1_ce1,
        OutPool3_1_q1,
        OutPool3_2_address0,
        OutPool3_2_ce0,
        OutPool3_2_q0,
        OutPool3_2_address1,
        OutPool3_2_ce1,
        OutPool3_2_q1,
        OutPool3_3_address0,
        OutPool3_3_ce0,
        OutPool3_3_q0,
        OutPool3_3_address1,
        OutPool3_3_ce1,
        OutPool3_3_q1,
        OutPool3_4_address0,
        OutPool3_4_ce0,
        OutPool3_4_q0,
        OutPool3_4_address1,
        OutPool3_4_ce1,
        OutPool3_4_q1,
        OutPool3_5_address0,
        OutPool3_5_ce0,
        OutPool3_5_q0,
        OutPool3_5_address1,
        OutPool3_5_ce1,
        OutPool3_5_q1,
        OutPool3_6_address0,
        OutPool3_6_ce0,
        OutPool3_6_q0,
        OutPool3_6_address1,
        OutPool3_6_ce1,
        OutPool3_6_q1,
        OutPool3_7_address0,
        OutPool3_7_ce0,
        OutPool3_7_q0,
        OutPool3_7_address1,
        OutPool3_7_ce1,
        OutPool3_7_q1,
        OutPool3_8_address0,
        OutPool3_8_ce0,
        OutPool3_8_q0,
        OutPool3_8_address1,
        OutPool3_8_ce1,
        OutPool3_8_q1,
        OutPool3_9_address0,
        OutPool3_9_ce0,
        OutPool3_9_q0,
        OutPool3_9_address1,
        OutPool3_9_ce1,
        OutPool3_9_q1,
        OutGlobalAverPool1D_address0,
        OutGlobalAverPool1D_ce0,
        OutGlobalAverPool1D_we0,
        OutGlobalAverPool1D_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] OutPool3_address0;
output   OutPool3_ce0;
input  [15:0] OutPool3_q0;
output  [5:0] OutPool3_address1;
output   OutPool3_ce1;
input  [15:0] OutPool3_q1;
output  [5:0] OutPool3_1_address0;
output   OutPool3_1_ce0;
input  [15:0] OutPool3_1_q0;
output  [5:0] OutPool3_1_address1;
output   OutPool3_1_ce1;
input  [15:0] OutPool3_1_q1;
output  [5:0] OutPool3_2_address0;
output   OutPool3_2_ce0;
input  [15:0] OutPool3_2_q0;
output  [5:0] OutPool3_2_address1;
output   OutPool3_2_ce1;
input  [15:0] OutPool3_2_q1;
output  [5:0] OutPool3_3_address0;
output   OutPool3_3_ce0;
input  [15:0] OutPool3_3_q0;
output  [5:0] OutPool3_3_address1;
output   OutPool3_3_ce1;
input  [15:0] OutPool3_3_q1;
output  [5:0] OutPool3_4_address0;
output   OutPool3_4_ce0;
input  [15:0] OutPool3_4_q0;
output  [5:0] OutPool3_4_address1;
output   OutPool3_4_ce1;
input  [15:0] OutPool3_4_q1;
output  [5:0] OutPool3_5_address0;
output   OutPool3_5_ce0;
input  [15:0] OutPool3_5_q0;
output  [5:0] OutPool3_5_address1;
output   OutPool3_5_ce1;
input  [15:0] OutPool3_5_q1;
output  [5:0] OutPool3_6_address0;
output   OutPool3_6_ce0;
input  [15:0] OutPool3_6_q0;
output  [5:0] OutPool3_6_address1;
output   OutPool3_6_ce1;
input  [15:0] OutPool3_6_q1;
output  [5:0] OutPool3_7_address0;
output   OutPool3_7_ce0;
input  [15:0] OutPool3_7_q0;
output  [5:0] OutPool3_7_address1;
output   OutPool3_7_ce1;
input  [15:0] OutPool3_7_q1;
output  [5:0] OutPool3_8_address0;
output   OutPool3_8_ce0;
input  [15:0] OutPool3_8_q0;
output  [5:0] OutPool3_8_address1;
output   OutPool3_8_ce1;
input  [15:0] OutPool3_8_q1;
output  [5:0] OutPool3_9_address0;
output   OutPool3_9_ce0;
input  [15:0] OutPool3_9_q0;
output  [5:0] OutPool3_9_address1;
output   OutPool3_9_ce1;
input  [15:0] OutPool3_9_q1;
output  [4:0] OutGlobalAverPool1D_address0;
output   OutGlobalAverPool1D_ce0;
output   OutGlobalAverPool1D_we0;
output  [11:0] OutGlobalAverPool1D_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln93_fu_345_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [5:0] i_reg_605;
wire    ap_block_pp0_stage0_11001;
reg   [5:0] i_reg_605_pp0_iter1_reg;
wire  signed [15:0] avg_1_fu_516_p2;
reg  signed [15:0] avg_1_reg_714;
reg   [0:0] tmp_reg_719;
wire   [63:0] zext_ln96_fu_367_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln96_1_fu_389_p1;
wire   [63:0] zext_ln93_fu_530_p1;
reg   [5:0] hs_fu_70;
wire   [5:0] add_ln93_1_fu_351_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_i;
reg    OutPool3_ce1_local;
reg    OutPool3_ce0_local;
reg    OutPool3_1_ce1_local;
reg    OutPool3_1_ce0_local;
reg    OutPool3_2_ce1_local;
reg    OutPool3_2_ce0_local;
reg    OutPool3_3_ce1_local;
reg    OutPool3_3_ce0_local;
reg    OutPool3_4_ce1_local;
reg    OutPool3_4_ce0_local;
reg    OutPool3_5_ce1_local;
reg    OutPool3_5_ce0_local;
reg    OutPool3_6_ce1_local;
reg    OutPool3_6_ce0_local;
reg    OutPool3_7_ce1_local;
reg    OutPool3_7_ce0_local;
reg    OutPool3_8_ce1_local;
reg    OutPool3_8_ce0_local;
reg    OutPool3_9_ce1_local;
reg    OutPool3_9_ce0_local;
reg    OutGlobalAverPool1D_we0_local;
wire   [11:0] select_ln98_1_fu_590_p3;
reg    OutGlobalAverPool1D_ce0_local;
wire   [5:0] shl_ln96_fu_361_p2;
wire   [4:0] trunc_ln96_fu_357_p1;
wire   [5:0] or_ln2_fu_381_p3;
wire   [15:0] add_ln96_1_fu_414_p2;
wire   [15:0] add_ln96_2_fu_420_p2;
wire   [15:0] add_ln96_fu_408_p2;
wire   [15:0] add_ln96_5_fu_438_p2;
wire   [15:0] add_ln96_6_fu_444_p2;
wire   [15:0] add_ln96_4_fu_432_p2;
wire   [15:0] add_ln96_7_fu_450_p2;
wire   [15:0] add_ln96_3_fu_426_p2;
wire   [15:0] add_ln96_10_fu_468_p2;
wire   [15:0] add_ln96_11_fu_474_p2;
wire   [15:0] add_ln96_9_fu_462_p2;
wire   [15:0] add_ln96_14_fu_492_p2;
wire   [15:0] add_ln96_15_fu_498_p2;
wire   [15:0] add_ln96_13_fu_486_p2;
wire   [15:0] add_ln96_16_fu_504_p2;
wire   [15:0] add_ln96_12_fu_480_p2;
wire   [15:0] add_ln96_17_fu_510_p2;
wire   [15:0] add_ln96_8_fu_456_p2;
wire   [17:0] mul_ln98_fu_537_p1;
wire   [33:0] mul_ln98_fu_537_p2;
wire   [32:0] trunc_ln98_fu_543_p1;
wire   [32:0] sub_ln98_fu_547_p2;
wire   [10:0] tmp_246_cast_fu_553_p4;
wire   [10:0] tmp_247_cast_fu_563_p4;
wire   [10:0] select_ln98_fu_573_p3;
wire   [11:0] zext_ln98_fu_580_p1;
wire   [11:0] sub_ln98_1_fu_584_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 hs_fu_70 = 6'd0;
#0 ap_done_reg = 1'b0;
end

CNN_mul_16s_18ns_34_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 18 ),
    .dout_WIDTH( 34 ))
mul_16s_18ns_34_1_1_U402(
    .din0(avg_1_reg_714),
    .din1(mul_ln98_fu_537_p1),
    .dout(mul_ln98_fu_537_p2)
);

CNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln93_fu_345_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            hs_fu_70 <= add_ln93_1_fu_351_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            hs_fu_70 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        avg_1_reg_714 <= avg_1_fu_516_p2;
        i_reg_605 <= ap_sig_allocacmp_i;
        i_reg_605_pp0_iter1_reg <= i_reg_605;
        tmp_reg_719 <= avg_1_fu_516_p2[32'd15];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        OutGlobalAverPool1D_ce0_local = 1'b1;
    end else begin
        OutGlobalAverPool1D_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        OutGlobalAverPool1D_we0_local = 1'b1;
    end else begin
        OutGlobalAverPool1D_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_1_ce0_local = 1'b1;
    end else begin
        OutPool3_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_1_ce1_local = 1'b1;
    end else begin
        OutPool3_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_2_ce0_local = 1'b1;
    end else begin
        OutPool3_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_2_ce1_local = 1'b1;
    end else begin
        OutPool3_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_3_ce0_local = 1'b1;
    end else begin
        OutPool3_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_3_ce1_local = 1'b1;
    end else begin
        OutPool3_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_4_ce0_local = 1'b1;
    end else begin
        OutPool3_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_4_ce1_local = 1'b1;
    end else begin
        OutPool3_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_5_ce0_local = 1'b1;
    end else begin
        OutPool3_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_5_ce1_local = 1'b1;
    end else begin
        OutPool3_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_6_ce0_local = 1'b1;
    end else begin
        OutPool3_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_6_ce1_local = 1'b1;
    end else begin
        OutPool3_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_7_ce0_local = 1'b1;
    end else begin
        OutPool3_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_7_ce1_local = 1'b1;
    end else begin
        OutPool3_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_8_ce0_local = 1'b1;
    end else begin
        OutPool3_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_8_ce1_local = 1'b1;
    end else begin
        OutPool3_8_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_9_ce0_local = 1'b1;
    end else begin
        OutPool3_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_9_ce1_local = 1'b1;
    end else begin
        OutPool3_9_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_ce0_local = 1'b1;
    end else begin
        OutPool3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPool3_ce1_local = 1'b1;
    end else begin
        OutPool3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln93_fu_345_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 6'd0;
    end else begin
        ap_sig_allocacmp_i = hs_fu_70;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OutGlobalAverPool1D_address0 = zext_ln93_fu_530_p1;

assign OutGlobalAverPool1D_ce0 = OutGlobalAverPool1D_ce0_local;

assign OutGlobalAverPool1D_d0 = select_ln98_1_fu_590_p3;

assign OutGlobalAverPool1D_we0 = OutGlobalAverPool1D_we0_local;

assign OutPool3_1_address0 = zext_ln96_1_fu_389_p1;

assign OutPool3_1_address1 = zext_ln96_fu_367_p1;

assign OutPool3_1_ce0 = OutPool3_1_ce0_local;

assign OutPool3_1_ce1 = OutPool3_1_ce1_local;

assign OutPool3_2_address0 = zext_ln96_1_fu_389_p1;

assign OutPool3_2_address1 = zext_ln96_fu_367_p1;

assign OutPool3_2_ce0 = OutPool3_2_ce0_local;

assign OutPool3_2_ce1 = OutPool3_2_ce1_local;

assign OutPool3_3_address0 = zext_ln96_1_fu_389_p1;

assign OutPool3_3_address1 = zext_ln96_fu_367_p1;

assign OutPool3_3_ce0 = OutPool3_3_ce0_local;

assign OutPool3_3_ce1 = OutPool3_3_ce1_local;

assign OutPool3_4_address0 = zext_ln96_1_fu_389_p1;

assign OutPool3_4_address1 = zext_ln96_fu_367_p1;

assign OutPool3_4_ce0 = OutPool3_4_ce0_local;

assign OutPool3_4_ce1 = OutPool3_4_ce1_local;

assign OutPool3_5_address0 = zext_ln96_1_fu_389_p1;

assign OutPool3_5_address1 = zext_ln96_fu_367_p1;

assign OutPool3_5_ce0 = OutPool3_5_ce0_local;

assign OutPool3_5_ce1 = OutPool3_5_ce1_local;

assign OutPool3_6_address0 = zext_ln96_1_fu_389_p1;

assign OutPool3_6_address1 = zext_ln96_fu_367_p1;

assign OutPool3_6_ce0 = OutPool3_6_ce0_local;

assign OutPool3_6_ce1 = OutPool3_6_ce1_local;

assign OutPool3_7_address0 = zext_ln96_1_fu_389_p1;

assign OutPool3_7_address1 = zext_ln96_fu_367_p1;

assign OutPool3_7_ce0 = OutPool3_7_ce0_local;

assign OutPool3_7_ce1 = OutPool3_7_ce1_local;

assign OutPool3_8_address0 = zext_ln96_1_fu_389_p1;

assign OutPool3_8_address1 = zext_ln96_fu_367_p1;

assign OutPool3_8_ce0 = OutPool3_8_ce0_local;

assign OutPool3_8_ce1 = OutPool3_8_ce1_local;

assign OutPool3_9_address0 = zext_ln96_1_fu_389_p1;

assign OutPool3_9_address1 = zext_ln96_fu_367_p1;

assign OutPool3_9_ce0 = OutPool3_9_ce0_local;

assign OutPool3_9_ce1 = OutPool3_9_ce1_local;

assign OutPool3_address0 = zext_ln96_1_fu_389_p1;

assign OutPool3_address1 = zext_ln96_fu_367_p1;

assign OutPool3_ce0 = OutPool3_ce0_local;

assign OutPool3_ce1 = OutPool3_ce1_local;

assign add_ln93_1_fu_351_p2 = (ap_sig_allocacmp_i + 6'd1);

assign add_ln96_10_fu_468_p2 = (OutPool3_3_q0 + OutPool3_4_q0);

assign add_ln96_11_fu_474_p2 = (add_ln96_10_fu_468_p2 + OutPool3_2_q0);

assign add_ln96_12_fu_480_p2 = (add_ln96_11_fu_474_p2 + add_ln96_9_fu_462_p2);

assign add_ln96_13_fu_486_p2 = (OutPool3_5_q0 + OutPool3_6_q0);

assign add_ln96_14_fu_492_p2 = (OutPool3_8_q0 + OutPool3_9_q0);

assign add_ln96_15_fu_498_p2 = (add_ln96_14_fu_492_p2 + OutPool3_7_q0);

assign add_ln96_16_fu_504_p2 = (add_ln96_15_fu_498_p2 + add_ln96_13_fu_486_p2);

assign add_ln96_17_fu_510_p2 = (add_ln96_16_fu_504_p2 + add_ln96_12_fu_480_p2);

assign add_ln96_1_fu_414_p2 = (OutPool3_3_q1 + OutPool3_4_q1);

assign add_ln96_2_fu_420_p2 = (add_ln96_1_fu_414_p2 + OutPool3_2_q1);

assign add_ln96_3_fu_426_p2 = (add_ln96_2_fu_420_p2 + add_ln96_fu_408_p2);

assign add_ln96_4_fu_432_p2 = (OutPool3_5_q1 + OutPool3_6_q1);

assign add_ln96_5_fu_438_p2 = (OutPool3_8_q1 + OutPool3_9_q1);

assign add_ln96_6_fu_444_p2 = (add_ln96_5_fu_438_p2 + OutPool3_7_q1);

assign add_ln96_7_fu_450_p2 = (add_ln96_6_fu_444_p2 + add_ln96_4_fu_432_p2);

assign add_ln96_8_fu_456_p2 = (add_ln96_7_fu_450_p2 + add_ln96_3_fu_426_p2);

assign add_ln96_9_fu_462_p2 = (OutPool3_q0 + OutPool3_1_q0);

assign add_ln96_fu_408_p2 = (OutPool3_1_q1 + OutPool3_q1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign avg_1_fu_516_p2 = (add_ln96_17_fu_510_p2 + add_ln96_8_fu_456_p2);

assign icmp_ln93_fu_345_p2 = ((ap_sig_allocacmp_i == 6'd32) ? 1'b1 : 1'b0);

assign mul_ln98_fu_537_p1 = 34'd104858;

assign or_ln2_fu_381_p3 = {{trunc_ln96_fu_357_p1}, {1'd1}};

assign select_ln98_1_fu_590_p3 = ((tmp_reg_719[0:0] == 1'b1) ? sub_ln98_1_fu_584_p2 : zext_ln98_fu_580_p1);

assign select_ln98_fu_573_p3 = ((tmp_reg_719[0:0] == 1'b1) ? tmp_246_cast_fu_553_p4 : tmp_247_cast_fu_563_p4);

assign shl_ln96_fu_361_p2 = ap_sig_allocacmp_i << 6'd1;

assign sub_ln98_1_fu_584_p2 = (12'd0 - zext_ln98_fu_580_p1);

assign sub_ln98_fu_547_p2 = (33'd0 - trunc_ln98_fu_543_p1);

assign tmp_246_cast_fu_553_p4 = {{sub_ln98_fu_547_p2[31:21]}};

assign tmp_247_cast_fu_563_p4 = {{mul_ln98_fu_537_p2[31:21]}};

assign trunc_ln96_fu_357_p1 = ap_sig_allocacmp_i[4:0];

assign trunc_ln98_fu_543_p1 = mul_ln98_fu_537_p2[32:0];

assign zext_ln93_fu_530_p1 = i_reg_605_pp0_iter1_reg;

assign zext_ln96_1_fu_389_p1 = or_ln2_fu_381_p3;

assign zext_ln96_fu_367_p1 = shl_ln96_fu_361_p2;

assign zext_ln98_fu_580_p1 = select_ln98_fu_573_p3;

endmodule //CNN_CNN_Pipeline_VITIS_LOOP_93_1
